apiVersion: v1
kind: Service
metadata:
  name: validation-app
spec:
  selector:
    app: validation-python
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 2000
    nodePort: 30306
  type: NodePort